flask_caching/__init__.py

Functions like `add`, `set`, etc usually return a boolean to indicate
whether the operation was successful. Currently, the wrappers throw that
return value away. Even `get_dict` does not return anything even though
it should.
This fixes issue #4.

Make wrappers return the wrapped results

---

tox.ini

The tox.ini file was set up to use unittest2 and unittest2py3k, which was kind of weird since unittest2 was really only necessary for python versions < 2.7 (the tox.ini only has versions >= 2.7). I modified the tox.ini to use nose, which is also already included in the requirements.txt and used by the .travis.yml.

modify tox.ini to use nose instead of unittest2, same as .travis.yml

---

.gitignore
CHANGES
flask_caching/__init__.py
test_cache.py

I don't know how this would work for *args but at least it works for kwargs ;)
If I find myself in the *args situation and this bugs, I'll propose a second patch

Fixed issue #18 : when function as **kwargs, keep unknown kwargs for key

---

flask_caching/__init__.py
test_cache.py

This addresses an issue where an app instance would
look at the wrong cache in a multi-app setup.
The last app passed to `cache.init_app` would stick around
and all the preceding apps would use its cache prefix.

return current_app by default from self.cache

---

flask_caching/__init__.py
test_cache.py

Provide a keyword `query_string` to `cached` decorator in order
to create the same cache key for different query string requests,
so long as they have the same key/value (order does not matter).
Create tests for aforementioned.

cached decorator takes query_string parameter

---

setup.py

This PR avoid breakage for environment with Werkzeug<0.12 already installed because the uwsgi backend depends on Werkzeug 0.12+

Specify Werkzeug version requirement (fix #37)

---

flask_caching/__init__.py
tests/test_view.py

This PR fixes a couple of issues I found with the `query_string=True` implementation
- Python 3 now randomizes `hash` on each start up. [Docs](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED) This means that if you reuse the cache across flask deploys or multiple apps deployed behind a load balancer, you will have extra cache misses.
- URL params can be repeated. The current implementation ignored that and built the cache from the first repeated url param

Support multiple params and use md5 for consistent hashing

---

flask_caching/__init__.py
tests/test_memoize.py

Currently there's no test case for using `delete_memoized` with arguments on a `@classmethod`.
Unfortunately the way you do that isn't very developer friendly, as you need to pass in the class itself as the first argument:
```
class Simulator(object):
@classmethod
@cache.memoize(5)
def position_of_star(cls, a, b):
return a + b + random.randrange(0, 100000)
cache.delete_memoized(Simulator.position_of_star, Simulator, 5, 2)
```
Because of that this PR also adds that an exception is raised if a class is not passed as the first argument to `delete_memoized`, when using it on a `@classmethod`.
It would be better to get the class some other way than forcing it to be passed in, but it seems that that's not possible:
https://stackoverflow.com/a/5075252 and https://stackoverflow.com/a/19228282 …

Raise an exception when using `delete_memoized` incorrectly on a classmethod

---

docs/index.rst

Werkzeug does not consistently handle options to its cache backends. We
clarify how flask-cache maintains configuration consistency where
possible and provide a workaround example.

Clarify usage of CONFIG_OPTIONS for various backends

---

.travis.yml

Also explicitly include "sudo: false" for faster container-based builds

Added pypy build targets in travis

---

.travis.yml

This should resolve the `coveralls: command not found` errors at the end of each travis build.

Fix travis coveralls support

---

flask_caching/__init__.py

This PR:
- Adds a Try Except to the memoize function that mirrors the functionality that exists in `cache`.  Basically if the application *cannot* reach the cache, it shouldn't error out, but rather return the call seamlessly without using the cache. This was done in the `cache` decorator but was never ported to the memoize function. 
- Also, noticed that when there is an exception, it checks to see if the app has debug enabled and if it does, raises the exception. However calling current app causes an exception itself, as it is not in the application context at that time. I changed these calls to use `self.app` instead which works as the cache is instantiated with the current app. Below is the error I was running into when current_app was called.
```
Traceback (most recent call last): …
```

Memoize Try Except

---

docs/index.rst

Documents existing support for Redis over TLS via the `CACHE_REDIS_URL` parameter.
Fixes #66.

Adds documentation about redis over TLS support

---

.gitignore
.travis.yml
docs/index.rst
flask_caching/backends/backends.py
flask_caching/backends/cache.py
flask_caching/backends/clients.py
tests/backends/cache/conftest.py
tests/backends/cache/test_backend_cache.py
tests/conftest.py
tests/test_basic_app.py
tox.ini

As per #72 , this PR simply removes the direct dependency on werkzeug.contrib.cache. As a first step, the werkzeug implementation has been adopted wholesale, and the rest of this library simply updated to use the correct import paths and to reflect that in the docs.
Going forward we may want to remove these and replace them with something similar, but as an immediate change to guard against werkzeug.contrib.cache's planned deprecation this PR makes no attempt to change or improve the cache backends themselves.

Deprecate werkzeug.contrib.cache

---

flask_caching/__init__.py
flask_caching/backends/cache.py
tests/backends/cache/test_backend_cache.py
tests/conftest.py
tests/test_cache.py
tests/test_memoize.py
tests/test_view.py

This PR resolves #65 by making the hashing function used a parameter in all functions/methods that used to be hard-coded to use md5.
This PR makes a change to all the tests that use affected methods to try with both md5 and sha256, but this might be overkill, tell me what you think @sh4nks and I'll take them out if you'd rather just an individual test or two to verify that multiple hash functions work.

parameterize the hash function so alternatives can be used

---

flask_caching/__init__.py

The `getfullargspec` function appears to return different values than that returned by `getargspec` (`keyword` in `getargspec` has changed to `varkw`), so actually attempting to provide an `unless` function with arguments to the `cached` decorator fails on python3.
In addition, the previous condition only allowed arguments to be passed through if the `unless` function took in at least one argument and variable positional and keyword args which seemed a little restrictive (what if the original only used kwargs?). Unless there is a good reason for doing this that I'm not aware of?
Let me know what you think about this @sh4nks !

Fix: Introspect python3 functions properly using varkw

---

flask_caching/__init__.py
tests/test_cache.py
tests/test_memoize.py

Don’t run cached/memoized function if the cached return value is None

---

.travis.yml
tox.ini

Python 3.7 is released as stable for a while now, there’s no need to have it pinned to a dev version.

Remove the -dev suffix from Python 3.7 in Tox and Travis

---

flask_caching/__init__.py
tests/test_cache.py
tests/test_memoize.py

Make the forced_update of @cached and @memoize accept the same parameters as the decorated function

---

tox.ini

This is useful run run only a few tests.

Allow to pass arguments to pytest via tox

---

tests/conftest.py

Currently it crashes with ImportError

Really skip xprocess if the module is not there

---

flask_caching/__init__.py
tests/test_memoize.py

This allows users to implement __caching_id__ as a class method to override the
default `repr` usage that does not suit all uses cases.

Allow to use __caching_id__ rather than __repr__ as an object caching key

---

flask_caching/backends/rediscache.py
tests/test_backend_cache.py

It's quite useful to use a function, instead of a string, as the `key_prefix`. This is especially useful when we want the cache to be unique based on GET query parameters. For more details, please see https://stackoverflow.com/questions/14228985/what-does-key-prefix-do-for-flask-cache.

RedisCache now supports function as a key_prefix

---

flask_caching/__init__.py
tests/test_memoize.py

Fixes #135 by allowing the user to specify if their function never returns None.  If so, we can safely assume a None returned from cache.get() means the key does not exist.

cache_none option for memoize to deal with concurrency problem

---

flask_caching/__init__.py
flask_caching/backends/rediscache.py
tests/test_cache.py

Secondary addition to #135 fix.  Original PR only included fix for memoize and not the cached function.

default cached to not cache None

---

docs/index.rst
flask_caching/backends/filesystem.py
flask_caching/backends/simple.py

There is a small typo in docs/index.rst, flask_caching/backends/filesystem.py, flask_caching/backends/simple.py.
Should read `occurred` rather than `occured`.

docs: Fix simple typo, occured -> occurred

---

flask_caching/backends/memcache.py
tests/test_backend_cache.py

Pylibmc expect the timeout to be provided as "number of seconds until the key expire", see http://sendapatch.se/projects/pylibmc/reference.html#pylibmc.Client.set
See more at https://github.com/sh4nks/flask-caching/issues/152

Bugfix: pylibmc expect time as delta time

---

flask_caching/__init__.py
tests/test_view.py

This PR is essentially a more considered version of #76 
After the additional discussion with @bzed I changed my stance on the functionality, but actually even further it seemed like what the library actually needed was a way to allow the consumer complete control over the cache key generation if they so wished.
I have added a `make_cache_key` parameter to the `cached` decorator for this purpose.
This should allow for use cases such as #71, an example of which is in the test added in this PR

add a `make_cache_key` parameter

---

docs/index.rst
flask_caching/__init__.py
tests/test_cache.py
tests/test_memoize.py
tests/test_view.py

Adding source_check option to Cache.cached to have it include the function's source code when forming the hash key to store along with the cached data.
Adding source check functionality to memoize.

Function source code hashing when generating cache key

---

flask_caching/backends/uwsgicache.py

Check in uWSGI options if cache2 was declared, without this the cache can't be used.

uWSGI: Check cache is enabled before use it & fix docstring

---

setup.py

Since this package is only compatible with Python 3, we should use the `python_requires` argument in `setup.py` so that tools like `pip` don't try to install it on unsupported versions of Python.
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
All other changes were automatically made by [`black`](https://github.com/psf/black) in my editor. I can revert them if you prefer.

setup.py: python_requires

---

flask_caching/__init__.py

Not pass the parameter `kwargs` in function `_memoize_make_cache_key`.`make_cache_key` when set forced_update.

Fix: Missing parameter `kwargs`

---

flask_caching/backends/memcache.py

SASLMemcachedCache: properly pass default_timeout to super constructor

---

setup.cfg

This PR fixes #189 and no longer marks wheel distributions as universal, as they are no longer py2 compatible.

Issue 189: stop marking wheels as py2 compatible

---

flask_caching/backends/filesystemcache.py
flask_caching/backends/simplecache.py
tests/test_cache.py

Log results of cache operations for SimpleCache and FileSystemCache as a first step toward improving observability (#182, #17). The remaining cache backends can be updated similarly in followup work as desired.
Also include some minor code improvements (see my review comments).
Run `pytest` with `--log-cli-level=debug` for a quick way to view example log output from these changes.
UPDATE: [All tests passed](https://travis-ci.com/github/jab/flask-caching/builds/204971572) on Travis. ✔️

Add some basic logging.

---

flask_caching/__init__.py
tests/test_memoize.py

This PR adds an option to ignore some arguments while generating the cache key.
i.e.
```python
@cache.memoize(50, args_to_ignore=["b"])
def big_foo(a, b):
return a + b + random.randrange(0, 100000)
assert big_foo(5, 3) == big_foo(5, 2)  # True
```

feat: Adds option in memoize to ignore args

---

flask_caching/__init__.py
flask_caching/backends/filesystemcache.py
flask_caching/backends/memcache.py
flask_caching/backends/rediscache.py
flask_caching/backends/simplecache.py
flask_caching/backends/uwsgicache.py
setup.cfg
setup.py

Add type annotations

---

flask_caching/backends/filesystemcache.py
tests/test_backend_cache.py

The set() method in FileSystemCache now checks if the file is new and only then increases file count. To my understanding, this only happened when caching a None value (this is why in the test case I added None values to the cache). I also fixed two locations where a cache file was deleted without updating the file count (in has() and get() methods).

Error in how FileSystemCache counts number of files #188

---

flask_caching/backends/rediscache.py

When there is no timeout, this resulted in the key expiring immediately after setting it, instead of not having an expiry at all.

Fix add() in RedisCache without a timeout

---

flask_caching/__init__.py
flask_caching/backends/__init__.py
flask_caching/backends/base.py
flask_caching/backends/filesystemcache.py
flask_caching/backends/memcache.py
flask_caching/backends/rediscache.py
flask_caching/backends/simplecache.py
flask_caching/backends/uwsgicache.py

This is a partial solution to #213

Move cache factory functionality into the cache backend classes.

---

docs/index.rst
examples/hello.cfg
flask_caching/__init__.py
tests/test_init.py

The condition to call `BaseCache.factory` was wrong; this PR fixes that, and adds some test to prevent regression.

Fix the factory method call for BaseCache derivatives

---

tests/test_backend_cache.py

Some serializers, like JSON, don't support byte strings and those need to be handled as a special case. It might be useful to test for that anyway.

Add test_generic_get_bytes

---

flask_caching/__init__.py
flask_caching/backends/base.py
flask_caching/backends/memcache.py
flask_caching/backends/nullcache.py
flask_caching/backends/simplecache.py

Quite useless, but I just fixed some typos that I've stumbled upon on some docstrings around the codebase.

docs: Fix trivial typos on docstrings

---

docs/index.rst

Just spotted this in my own usage of Flask-Caching

Fix typo in filesystem cache type in docs

---

MANIFEST.in

Add missing py.typed file

---

CHANGES.rst
src/flask_caching/backends/rediscache.py

It was wrong parsing not _sentinel__ CACHE_OPTIONS in RedisSentinelCache
- fixes #343 
Checklist:

Fixes #343 bug

---

CHANGES.rst
src/flask_caching/__init__.py

Our 1.11.0 release 🎉 
**Change summary**
- Add suport for cached/memoized generators. PR `#286 <https://github.com/pallets-eco/flask-caching/pull/286>`_.
- Add support for Flask 2.0 async. PR `#282 <https://github.com/pallets-eco/flask-caching/pull/282>`_.
- Cachelib is now used as backend. PR `#308 <https://github.com/pallets-eco/flask-caching/pull/308>`_.
- Drop support for python 3.6. PR `#332 <https://github.com/pallets-eco/flask-caching/pull/332>`_.
- Add support for dynamic cache timeouts `#296 <https://github.com/pallets-eco/flask-caching/pull/296>`_.
- Fix bug in CACHE_OPTIONS reading for radis in RedisSentinelCache

release 11.0.1

---

setup.py

Since #308 added a hard requirement for `cachelib`, add it to user-facing `setup.py` as well (it was previously only added to dev-dependencies).
I'm not gonna run this whole test suite, sorry. You pushed a broken release 0.11.0, please phixit ;)
To avoid similar issues in the future, it would probably be better to put non-dev requirements into `requirements/prod.in` and generate regular `requirements.txt` from that. Also remove `cachelib` and other non-test deps from `test.in` and instead `-r prod.in`. But that's for you to decide. 
--- 
Checklist:

requirements: Add cachelib dependency

---

CHANGES.rst
src/flask_caching/__init__.py

Our 2.0.0 release 🎉 
Change Summary:
- fix bug where ``flask_caching.backends.RedisSentinelCache.get_many`` would query wrong host&port combination. :pr:`372`
- ``flask_caching.backends.FileSystemCache`` internal implementations have been removed. It now shares 100% of ``cachelib.FileSystemCache`` API and is fully compatible. :pr:`369`
- Add proxy to underlaying ``has`` method of cache clients. :pr:`356`

release 2.0.0

---

CHANGES.rst
setup.py

... to minor version that's compatible
fix #388 #382

Relax Flask version restriction

---

CHANGES.rst
src/flask_caching/__init__.py

Our 2.0.1 release 🎉 
**Change summary:**
- Relax dependency pin to allow Flask 2.x.x

release 2.0.1

---

src/flask_caching/__init__.py

Fix type annotations in the `Cache` class as pointed out by mypy.
- See #384 (this PR alone does not fix it completely)
Checklist:

Fix type annotation errors in Cache

---

docs/index.rst
tests/test_view.py

There are small typos in:
- docs/index.rst
- tests/test_view.py
Fixes:
- Should read `threshold` rather than `treshold`.
- Should read `override` rather than `overide`.
- Should read `ability` rather than `ablity`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

setup.py

As of now flask-caching doesn't support latest cachelib release where DynamoDB backend has been added, for now I'll go ahead and pin cachelib to < 0.10.0 until I get around to make the necessary changes to allow for the use of the new backend.

Pin cachelib to previous release

---

CHANGES.rst
src/flask_caching/__init__.py
tests/test_view.py

fixes #97. this matches how memoize already does the same thing:
https://github.com/pallets-eco/flask-caching/blob/b526e03edf0602d10d9cf938b955a59b521636ad/src/flask_caching/__init__.py#L838
Checklist:
- N/A Add or update relevant docs, in the docs folder and in code.
- N/A Add `.. versionchanged::` entries in any relevant code docs.

bug fix: make cached view function make_cache_key attr writeable

---

.github/workflows/tests.yml
CHANGES.rst
src/flask_caching/__init__.py
tox.ini

Our 2.0.2 released 🎉 
This is a hotfix release to address issues with latest cachelib.
**Change Summary**
- avoid issue with `boto3` dependency on flask_caching import due to latest cachelib released 
- migrate ``flask_caching.backends.RedisCluster`` dependency from redis-py-cluster to redis-py
- bug fix: make the ``make_cache_key`` attributed of decorated view functions writeable. :pr:`431`, issue `#97`

Release 2.0.2

---

CHANGES.rst
docs/index.rst

`make_cache_key` was missing from the docs.
adding for reference. 
Pl see
https://github.com/pallets-eco/flask-caching/issues/222
- fixes #222 
Checklist:
- [N/A] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [N/A] Add `.. versionchanged::` entries in any relevant code docs.
- [N/A] Run `pre-commit` hooks and fix any issues.
- [N/A] Run `pytest` and `tox`, no tests failed.

make_cache_key docs and example added

---

docs/index.rst

Include default values for settings
https://github.com/pallets-eco/flask-caching/blob/master/src/flask_caching/__init__.py#L106-L109
- fixes #202

Update index.rst to include default values for settings

---

CHANGES.rst
src/flask_caching/__init__.py

Our 2.1.0 release 🎉 
**Change summary**
- fix type signature in ``flask_caching.utils.make_template_fragment_key``. :pr:`430`
- Added docs and example for make_cache_key
- we now support Flask 3

release 2.1.0

---

src/flask_caching/backends/rediscache.py
tests/test_backend_cache.py

This removal an addition to this PR : https://github.com/pallets-eco/flask-caching/pull/109.
The main goal is to reintroduce an old behaviour : the possibility to give a function to the key_prefix RedisCache parameter. 
This behaviour is reintroduced in the cachelib library (https://github.com/pallets-eco/cachelib/pull/332).

Remove unused _get_prefix() method from RedisCache class.

---

docs/index.rst

Replace deprecated cache type names `filesystem` and `simple` with new names `FileSystemCache` and `SimpleCache`.

Update cache type names in index.rst

---

src/flask_caching/__init__.py
tests/test_memoize.py

This PR introduces a one-line change that forces the `memoize` function to respect keyword arguments when `args_to_ignore` is supplied.
- fixes #557
Checklist:

Respect kwargs when args_to_ignore is set in memoize

---

CHANGES.rst
src/flask_caching/__init__.py

Our 2.2.0 release 🎉 
some house keeping stuff
- added python 3.11 to supported array
- drop python 3.7 (long overdue)
- Fix issue causing `args_to_ignore` to not work with `flask_caching.Cache.memoize` decorator when keyword arguments were used in the decorated function call

Release 2.2.0

---

CHANGES.rst
src/flask_caching/__init__.py

Our 2.3.0 release 🎉 
- Added ``response_hit_indication`` flag to ``Cache.cached`` decorator for appending 'hit_cache' headers to responses, indicating cache hits.

Release 2.3.0
